### ISSUE TITLE
Add createElement

### ISSUE THREAD

**Issue by ashur** [ashur/eleventy-toolkit#11]
## Description

A paired shortcode that makes it less cumbersome to generate HTML elements with conditional tag names and attributes.

### Example

```njk
{% createElement "a" if link, { href: link } %}
    {# Complex innerHTML #}
    {{ item1 }}
    {{ item2 }}
    {{ item3 }}
    {{ item4 }}
    {{ item5 }}
{% endcreateElement %}
```

If `link` is defined — ex., `https://example.com` — innerHTML is wrapped in an `<a>` element:

```njk
<a href="https://example.com">
    {# Complex innerHTML #}
    {{ item1 }}
    {{ item2 }}
    {{ item3 }}
    {{ item4 }}
    {{ item5 }}
</a>
```

If not, only the innerHTML is returned:

```
{# Complex innerHTML #}
{{ item1 }}
{{ item2 }}
{{ item3 }}
{{ item4 }}
{{ item5 }}
```

## Tasks

- [x] Create unit tests
- [x] Document usage in [`shortcodes/README.md`](https://github.com/ashur/eleventy-toolkit/blob/main/src/shortcodes/README.md)
- [x] Update [CHANGELOG](https://github.com/ashur/eleventy-toolkit/blob/main/CHANGELOG.md)
